import { MeshyImage3DTask } from "./meshy";

export const PRELOADED_EXAMPLES: MeshyImage3DTask[] = [
  {
    id: "ex-male-bust",
    type: "3d",
    name: "Realistic Male Bust",
    badge: "EXAMPLE",
    status: "SUCCEEDED",
    progress: 100,
    topology: "Triangle",
    thumbnail_url: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=400&q=80",
    model_urls: {
      glb: "https://modelviewer.dev/shared-assets/models/NeilArmstrong.glb",
      obj: "https://modelviewer.dev/shared-assets/models/NeilArmstrong.glb",
      fbx: "https://modelviewer.dev/shared-assets/models/NeilArmstrong.glb",
      usdz: "https://modelviewer.dev/shared-assets/models/NeilArmstrong.glb",
      stl: "https://modelviewer.dev/shared-assets/models/NeilArmstrong.glb",
    },
    statistics: {
      faces: 2841020,
      vertices: 1420510,
    },
    created_at: Date.now() - 3600000,
  },
  {
    id: "ex-hooded-teal",
    type: "3d",
    name: "Hooded Teal-Hair Character",
    badge: "EXAMPLE",
    status: "SUCCEEDED",
    progress: 100,
    topology: "Triangle",
    thumbnail_url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=400&q=80",
    model_urls: {
      glb: "https://modelviewer.dev/shared-assets/models/Astronaut.glb",
      obj: "https://modelviewer.dev/shared-assets/models/Astronaut.glb",
      fbx: "https://modelviewer.dev/shared-assets/models/Astronaut.glb",
      usdz: "https://modelviewer.dev/shared-assets/models/Astronaut.usdz",
      stl: "https://modelviewer.dev/shared-assets/models/Astronaut.glb",
    },
    statistics: {
      faces: 3133220,
      vertices: 1631084,
    },
    created_at: Date.now() - 600000,
  },
  {
    id: "ex-anime-pink-cap",
    type: "3d",
    name: "Anime Girl in Pink Cap",
    badge: "TEMPLATE",
    status: "SUCCEEDED",
    progress: 100,
    topology: "Triangle",
    thumbnail_url: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=400&q=80",
    model_urls: {
      glb: "https://modelviewer.dev/shared-assets/models/RobotExpressive.glb",
      obj: "https://modelviewer.dev/shared-assets/models/RobotExpressive.glb",
      fbx: "https://modelviewer.dev/shared-assets/models/RobotExpressive.glb",
      usdz: "https://modelviewer.dev/shared-assets/models/RobotExpressive.glb",
      stl: "https://modelviewer.dev/shared-assets/models/RobotExpressive.glb",
    },
    statistics: {
      faces: 1980420,
      vertices: 990210,
    },
    created_at: Date.now() - 1500000,
  },
  {
    id: "ex-circular-medallion",
    type: "3d",
    name: "Red Circular Medallion",
    badge: "TEMPLATE",
    status: "SUCCEEDED",
    progress: 100,
    topology: "Triangle",
    thumbnail_url: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=400&q=80",
    model_urls: {
      glb: "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/MaterialsVariantsShoe/glTF-Binary/MaterialsVariantsShoe.glb",
      obj: "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/MaterialsVariantsShoe/glTF-Binary/MaterialsVariantsShoe.glb",
      fbx: "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/MaterialsVariantsShoe/glTF-Binary/MaterialsVariantsShoe.glb",
      usdz: "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/MaterialsVariantsShoe/glTF-Binary/MaterialsVariantsShoe.glb",
      stl: "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/MaterialsVariantsShoe/glTF-Binary/MaterialsVariantsShoe.glb",
    },
    statistics: {
      faces: 842100,
      vertices: 421050,
    },
    created_at: Date.now() - 2400000,
  },
  {
    id: "ex-leather-backpack",
    type: "3d",
    name: "Brown Leather Backpack",
    badge: "EXAMPLE",
    status: "SUCCEEDED",
    progress: 100,
    topology: "Triangle",
    thumbnail_url: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=400&q=80",
    model_urls: {
      glb: "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/DamagedHelmet/glTF-Binary/DamagedHelmet.glb",
      obj: "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/DamagedHelmet/glTF-Binary/DamagedHelmet.glb",
      fbx: "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/DamagedHelmet/glTF-Binary/DamagedHelmet.glb",
      usdz: "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/DamagedHelmet/glTF-Binary/DamagedHelmet.glb",
      stl: "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/DamagedHelmet/glTF-Binary/DamagedHelmet.glb",
    },
    statistics: {
      faces: 1450200,
      vertices: 725100,
    },
    created_at: Date.now() - 7200000,
  },
  {
    id: "ex-viking-warrior",
    type: "3d",
    name: "Viking Warrior Character",
    badge: "EXAMPLE",
    status: "SUCCEEDED",
    progress: 100,
    topology: "Triangle",
    thumbnail_url: "https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=400&q=80",
    model_urls: {
      glb: "https://modelviewer.dev/shared-assets/models/Astronaut.glb",
      obj: "https://modelviewer.dev/shared-assets/models/Astronaut.glb",
      fbx: "https://modelviewer.dev/shared-assets/models/Astronaut.glb",
      usdz: "https://modelviewer.dev/shared-assets/models/Astronaut.usdz",
      stl: "https://modelviewer.dev/shared-assets/models/Astronaut.glb",
    },
    statistics: {
      faces: 3450900,
      vertices: 1725450,
    },
    created_at: Date.now() - 10800000,
  },
  {
    id: "ex-potion-flask",
    type: "3d",
    name: "Fantasy Potion Flask",
    badge: "EXAMPLE",
    status: "SUCCEEDED",
    progress: 100,
    topology: "Triangle",
    thumbnail_url: "https://images.unsplash.com/photo-1514733670139-4d87a1941d55?auto=format&fit=crop&w=400&q=80",
    model_urls: {
      glb: "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/WaterBottle/glTF-Binary/WaterBottle.glb",
      obj: "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/WaterBottle/glTF-Binary/WaterBottle.glb",
      fbx: "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/WaterBottle/glTF-Binary/WaterBottle.glb",
      usdz: "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/WaterBottle/glTF-Binary/WaterBottle.glb",
      stl: "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/WaterBottle/glTF-Binary/WaterBottle.glb",
    },
    statistics: {
      faces: 620400,
      vertices: 310200,
    },
    created_at: Date.now() - 18000000,
  },
  {
    id: "ex-stone-axe",
    type: "3d",
    name: "Stone Axe Weapon",
    badge: "EXAMPLE",
    status: "SUCCEEDED",
    progress: 100,
    topology: "Triangle",
    thumbnail_url: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=400&q=80",
    model_urls: {
      glb: "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/BoomBox/glTF-Binary/BoomBox.glb",
      obj: "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/BoomBox/glTF-Binary/BoomBox.glb",
      fbx: "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/BoomBox/glTF-Binary/BoomBox.glb",
      usdz: "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/BoomBox/glTF-Binary/BoomBox.glb",
      stl: "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/BoomBox/glTF-Binary/BoomBox.glb",
    },
    statistics: {
      faces: 1120800,
      vertices: 560400,
    },
    created_at: Date.now() - 86400000,
  },
];
